#!/usr/bin/env bash
# Shared reporting for the numbered scripts. No dependencies, no eval, no secrets.
# Outside bootstrap, messages still go to the terminal. During bootstrap, the
# parent captures output and reads these explicit records for its final summary.

report_warning() {
  printf 'WARNING: %s\n' "$*" >&2
  if [ -n "${BOOTSTRAP_REPORT_DIR:-}" ]; then
    printf '%s: %s\n' "${BOOTSTRAP_STAGE:-setup}" "$*" >>"$BOOTSTRAP_REPORT_DIR/warnings"
    : >"$BOOTSTRAP_REPORT_DIR/stages/${BOOTSTRAP_STAGE:-setup}.warning"
  fi
}

# Stable ID, title, then one or more human-readable instruction lines.
report_action() {
  case "$1" in ''|*[!a-zA-Z0-9_-]*) return 2 ;; esac
  if [ -n "${BOOTSTRAP_REPORT_DIR:-}" ]; then
    report_action_id=$1
    shift
    printf '%s\n' "$@" >"$BOOTSTRAP_REPORT_DIR/actions/$report_action_id"
    : >"$BOOTSTRAP_REPORT_DIR/stages/${BOOTSTRAP_STAGE:-setup}.action"
  else
    shift
    printf '%s\n' "$@"
  fi
}

report_deferred() {
  if [ -n "${BOOTSTRAP_REPORT_DIR:-}" ]; then
    : >"$BOOTSTRAP_REPORT_DIR/stages/${BOOTSTRAP_STAGE:-setup}.deferred"
  fi
}

# Bash callers use %q so paths with spaces/quotes are safe to paste into Bash.
report_keys_action() {
  local rerun
  printf -v rerun 'bash %q' "$SCRIPT_DIR/5 Keys.sh"
  report_action ssh-keys '1Password → SSH keys' \
    'Sign into the 1Password app; enable Settings → Developer → Integrate with 1Password CLI.' \
    'Alternatively, in Bash: op account add, then eval "$(op signin)"' \
    'Verify: op whoami' "Rerun (Bash): $rerun"
}

report_linear_action() {
  local setup="$HOME/.config/omarchy/plugins/andres.linear/bin/omarchy-linear-setup"
  local config="${LINEAR_OMARCHY_CONFIG:-$HOME/.config/omarchy/linear/config.lua}"
  local token_file="${LINEAR_OMARCHY_TOKEN_FILE:-${XDG_DATA_HOME:-$HOME/.local/share}/omarchy/linear/token}"
  local key_state=unknown items='' quoted_setup
  [ -x "$setup" ] || return 0

  # Search keyring metadata only. Unlike `setup check` / `secret-tool lookup`,
  # SearchItems never requests a secret or unlocks a collection. No network call.
  if command -v gdbus >/dev/null 2>&1; then
    if items=$(gdbus call --session --timeout 3 --dest org.freedesktop.secrets \
      --object-path /org/freedesktop/secrets \
      --method org.freedesktop.Secret.Service.SearchItems \
      "{'service': 'linear-omarchy', 'account': 'api'}" 2>/dev/null); then
      key_state=missing
      case "$items" in *'/org/freedesktop/secrets/'*) key_state=locked ;; esac
      case "${items%%],*}" in *'/org/freedesktop/secrets/'*) key_state=present ;; esac
    fi
  fi
  if [ -s "$token_file" ] && [ -r "$token_file" ]; then
    case "$(stat -c '%a' "$token_file" 2>/dev/null)" in
      600|400) key_state=present ;;
    esac
  fi

  if [ "$key_state" = present ] && [ -f "$config" ] && \
    grep -Eq '^[[:space:]]*team(_id)?[[:space:]]*=[[:space:]]*"[^"]+"' "$config" && \
    grep -Eq '^[[:space:]]*project(_id)?[[:space:]]*=[[:space:]]*"[^"]+"' "$config"; then
    return 0
  fi

  printf -v quoted_setup '%q' "$setup"
  report_action linear 'Linear → API key + team/project' \
    "Configuration missing/incomplete, or stored API key not confirmed ($key_state)." \
    'If the login keyring is locked, unlock it first.' \
    "Store a key if needed: $quoted_setup key" \
    "Verify access: $quoted_setup check" \
    "List targets: $quoted_setup list" \
    "Choose target: $quoted_setup use \"Team\" \"Project\"" \
    "Config file (generated by use; optional manual edits): $config" \
    'The API key belongs in the login keyring, not config.lua.'
}
